all: Dihotom.class
	java  -cp .:/usr/share/junit-4/lib/junit.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar org.junit.runner.JUnitCore Dihotom

Dihotom.class: Dihotom.java
	javac -cp .:/usr/share/junit-4/lib/junit.jar Dihotom.java
